### ISSUE TITLE
Issue with example.py

### ISSUE THREAD

**Issue by nraghuveer** [prius/python-leetcode#17]
![image](https://user-images.githubusercontent.com/8545379/147395976-bff2e21c-f5ed-48f7-9e56-b556ab7f91b8.png)

There seems to some API issue with leetcode.GraphqlVariables.

![image](https://user-images.githubusercontent.com/8545379/147395985-4d3cd829-5c7c-46ff-98d4-19d69784ae78.png)

**Comment by prius** [comment]
Hi @nraghuveer 

Thanks for mentioning that. I think `example.py` became outdated after I added unittests. I will work on updating it and adding references to unittests instead.

Unittests added (you can use them as examples):
* https://github.com/prius/python-leetcode/blob/main/test/test_graphql_request_get_question_detail.py
* https://github.com/prius/python-leetcode/blob/main/test/test_graphql_request_problemset_question_list.py

Also, example usage can be found in these repo https://github.com/prius/leetcode-anki

Hope this helps and will try to update this repo asap.

**Comment by nraghuveer** [comment]
Great! Thanks!
However, I have a question, I am new to this GraphQL, and from seeing the examples you just mentioned, I am wondering if it is possible to do the queries that are not yet defined in the package? Like, I am trying to extract "note" information for a given question slug. Is it possible with existing api or does it need a development?
